import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Buyer Agreement - zoozle.in",
  description:
    "Buyer Agreement for zoozle.in. Read and understand the terms and conditions for purchasing products or services on our platform.",
};
function buyersTermsAndConditions() {
  return (
    <div className="container mt-5 text-justify md:px-0 px-3 text-[14px]">
      <div className="row justify-content-lg-between align-items-lg-center">
        <div className="col-md-12">
          <p className="font-bold text-center pt-6 text-[16px] underline">
            Buyer Agreement and Terms and Conditions
          </p>
          <br />
          <p className="underline ">
            <i> Effective Date (Last Updated): January-25, 2023.</i>
          </p>
          <br />

          <p>
            Welcome to
            <i>
              <b> Zoozle</b>{" "}
            </i>
            ’s
            <i>
              <b>Buyer Agreement &amp; Terms &amp; Conditions</b>{" "}
            </i>
            .
          </p>
          <p className="py-2">
            This <span className="s4">document </span>is an electronic record in
            terms of Information Technology Act, 2000 (“
            <b>IT Act, 2000</b>”), the applicable rules thereunder and the
            provisions pertaining to electronic records in various statutes and
            as amended by the IT Act, 2000, from time to time. This electronic
            record is generated by a computer system and does not require any
            physical or digital signatures.
          </p>
          <p className="py-2">
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Intermediary Guidelines and
            Digital Media Ethics Code) Rules, 2021 that require publishing the
            rules and regulations, Privacy Policy and Terms of Use for access to
            or usage of
            <span>
              <Link href="/" className="s6" target="_blank">
                {" "}
                www.zoozle.in
              </Link>
            </span>
            <span>website.</span>
          </p>
          <p className="py-2">
            The domain name
            <Link href="/" className="a" target="_blank">
              www.zoozle.in
            </Link>
            , including the related mobile site and mobile application as well
            as the Seller portal (seller.zoozle.com (hereinafter referred to as
            “<b>Zoozle Platform</b>”) is owned and operated by Zoozle Tech
            Private Limited, a private limited company, incorporated and
            registered under the Companies Act, 2013, having its registered
            office at No. 30/1, 4th Floor, Leemans Complex, Cunningham Road,
            Bangalore, Karnataka, India. (hereinafter, referred to as “{" "}
            <b>Zoozle</b>” and for all purposes, the personal pronouns like “{" "}
            <b>we</b>,” “ <b>us</b>,” “ <b>our</b>” be used).
          </p>
          <p className="py-2">
            The word ‘User’ shall collectively imply a Seller, a Buyer, and any
            visitor on the Zoozle Platform seeking/requiring Products through
            the Zoozle Platform and any other websites (hereinafter collectively
            referred to as “ <b>Site</b>”) through which Zoozle makes the “{" "}
            <b>Zoozle E-Commerce Enabler Services</b>” available, subject to
            this “ <b>Buyers Agreement</b>” &amp; ‘{" "}
            <b>Terms &amp; Conditions</b>” (hereinafter referred to as “
            <b>Buyers Terms</b>” or “ <b>Terms</b>”) including applicable
            policies available on the Zoozle Platform, notifications and
            communications sent to You on the Zoozle Platform which are
            incorporated herein by way of reference. If You transact on the
            Zoozle Platform, You shall be subject to the policies that are
            applicable to the Zoozle Platform for such a transaction. By mere
            use of the Zoozle Platform, You shall be contracting with Zoozle,
            and these terms and conditions including the policies constitute
            Your binding obligations to Zoozle. For the purpose of the Buyer
            Terms, wherever the context so requires, ‘ <b>You</b>’ and ‘{" "}
            <b>Your</b>’ shall relate to any natural or legal person who has
            agreed to become a Buyer on the Platform by providing registration
            data while registering on the Platform using computer systems.
          </p>
          <p className="py-2">
            When You use any current or future services provided by us through
            the Zoozle Platform, You will be subject to the rules, guidelines,
            policies, terms and conditions applicable to such services and they
            shall be deemed incorporated into the Buyers Terms and considered a
            part and parcel of the Buyers Terms. We reserve the right, at our
            sole discretion, to change, modify, add, or remove portions of the
            Buyer Terms at any time. We will notify You through any of the
            communication modes as mentioned in this Buyer Terms in case of any
            changes or updates to the Buyer Terms that materially impact Your
            use of the Zoozle Platform. Your continued use of the Zoozle
            Platform following the changes or updates will mean that You accept
            and agree to the revisions. As long as, You comply with the Terms,
            we grant You a personal, non-exclusive, non-transferable, and
            limited privilege to enter and use the Zoozle Platform.
          </p>
          <br />
          <p className="font-bold">
            ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR
            AGREEMENT WITH ALL THE TERMS AND CONDITIONS UNDER THE BUYER TERMS.
          </p>
          <p className="font-bold">
            PLEASE READ THE TERMS CAREFULLY BEFORE PROCEEDING. By implicitly or
            expressly
          </p>
          <p>
            accepting the Buyer Terms, You also accept and agree to be bound by
            all of Zoozle’s policies applicable to You, as amended, from time to
            time.
          </p>
          <br />
          <p>
            The Zoozle Platform and Zoozle E-Commerce Enabler comprise an online
            platform through which the Seller may create Listed Products that
            You may learn about, connect, and buy Listed Products directly from
            the Seller or through Zoozle entrepreneurs. You understand and agree
            that Zoozle is not a party to any agreements entered into between{" "}
            <i>Seller </i>and <i>You</i>, nor is Zoozle a provider of any goods
            and/or Listed Products and/or services, an agent or insurer. Zoozle
            cannot and has no control over the content contained in any Listed
            Products and the condition, legality or suitability of any Listed
            Products and the conduct of Seller
            <i>
              <b>. </b>{" "}
            </i>
            Zoozle is not responsible for any/all Listed Products and disclaims
            any and all liability related to the maximum extent permitted by law
            for any/all Listed Products. Accordingly, any sales accepted will be
            at Your own risk.
          </p>
          <br />
          <p className="underline font-bold text-[16px]">
            Interpretations &amp; Definitions
          </p>
          <br />
          <p>
            Clauses in this Terms are inserted for convenience only and shall
            not be used in its interpretation unless inserted for specific
            meaning/s. In these Terms, unless the context clearly indicates a
            contrary intention, a word or an expression which denotes a natural
            person shall include an artificial person (and vice versa), any one
            gender shall include the other genders, the singular shall include
            the plural (and vice versa) and the following words and expressions
            shall bear the meanings assigned to them below (and cognate words
            and expressions shall bear corresponding meanings):
          </p>
          <br />
          <p>
            “<b>Affiliate” </b>means with respect to a person, any other person
            which directly or indirectly controls, or is controlled by, or is
            under common control with, the specified person. For purposes of the
            preceding sentence, “control” of a person shall mean the possession,
            directly or indirectly, of the power to direct or cause the
            direction of the management or policies of such person, or direct or
            indirect ownership (beneficially or of record) of, or direct or
            indirect power to vote, 50% (fifty percent) or more of the
            outstanding shares of any class of capital stock of such person (or
            in the case of a person that is not a corporation, 50% (fifty
            percent) or more of any class of equity interest).
          </p>
          <br />
          <p>
            “<b>Applicable Law</b>” means any Indian statute, law, ordinance,
            regulation, rule, order, bye law, administrative interpretation,
            writ, injunction, directive, judgment or decree or other instrument
            which is for the time being in force in India.
          </p>

          <br />

          <p>
            “<b>Buyer</b>” means independent person, individual, firm or company
            or any organization or any legal entity of existence under the
            governance of the country, who visits or uses our Site in order to
            avail/ buy and receive Listed Products offered by the Seller and is
            available on our Site, application and Platform Services for
            monetary compensation / consideration.
          </p>
          <br />
          <p>
            &quot;<b>Collective Content</b>&quot; means Seller Content and Zoozle Content.
          </p>
          <br />
          <p>
            &quot;<b>Content</b>&quot; means text, graphics, images, audio, video,
            software (excluding the <i>application</i>), information or other
            materials of promotion of the Listed Products displayed by the
            Seller for sale, on the Site, application, and Zoozle Platform
            Services <b>.</b>
          </p>
          <br />
          <h1>
            <b>“Deliverables”</b>
            <span className="p">
              means any quantum of Listed Products agreed and provided (for an
              agreed monetary compensation/consideration) and to be delivered by
              the Seller to a Buyer to complete the sale.
            </span>
          </h1>

          <br />

          <p className="s3">
            “<span className="font-bold">Intellectual Property</span>”
            <span className="p">
              means trade name, trademark, logo, copyright, service mark used by
              Zoozle in relation to its business and any other form of
              intellectual property.
            </span>
          </p>
          <p>
            “<b>Jurisdiction</b>” means the authority of the courts of Bangalore
            city, Karnataka, INDIA, only, in case of any legal
            implication/cases.
          </p>
          <br />
          <p>
            &quot;<b>Listed Products</b>&quot; means an offer to sell and deliver products
            that is posted by a Seller via the Zoozle Platform.
          </p>
          <br />
          <p>
            &quot;<b>Seller Content</b>&quot; means all Content that a Seller posts,
            uploads, publishes, submits, transmits, or includes in their Listed
            Products or Seller profile to be made available through the Zoozle
            Platform.
          </p>
          <br />
          <p>
            “<b>Platform” </b>means the information technology online platform
            with related technology and applications that operates the Site
            &amp; application of Zoozle
            <i>
              <b>.</b>
            </i>
          </p>
          <br />
          <p>
            “<b>Platform Services” </b>means any services offered to the Buyers
            through ‘Zoozle’ and including but not limited to providing end to
            end IT solutions by offering the Zoozle Platform to the Buyers to
            make their selection vide a variety of options, shortlisting the
            Seller and placing orders, providing payment gateways vide third
            party/ies, providing technology solutions, interactions via email,
            phone, messaging services etc. and providing ancillary services to
            the Buyers.
          </p>
          <br />
          <p>
            “<b>Products</b>” shall mean the product purchased by the Buyer from
            the Seller through Zoozle Platform.
          </p>
          <br />
          <p>
            “<b>Seller</b>” means independent person, individual, firm or
            company or any organization or any legal entity of existence under
            the governance of the country, who is providing Listed Products to
            Buyer through the Zoozle Platform and who is accepted by Zoozle for
            the purpose of providing such Platform Services.
          </p>
          <br />
          <h1>
            <b>“SNS” </b>
            <span className="p">
              means certain third-party Social Networking Sites (
            </span>
            SNS
            <span className="p">
              ) (including, but not limited to, all third parties through which
              You access our Site, application, and Platform Services
            </span>
            <i>.</i>
          </h1>
          <br />
          <p>
            “<b>Sale Price” </b>means the total price in INR (inclusive of taxes
            but can/may be shown, calculated, and added separately) quoted and
            displayed by the Seller on Zoozle Platform
            <i>
              <b>, </b>{" "}
            </i>
            to the Buyer who wishes to avail the Listed Products from an
            approved Seller on the Zoozle Platform
            <i>
              <b>.</b>
            </i>
          </p>
          <br />
          <h1>
            <b>
              <i>“Buyer Terms” </i>{" "}
            </b>
            <span className="p">means the entirety of this ‘</span>Terms and
            Conditions
            <span className="p">’. “</span>Zoozle Account
            <span className="p">
              ” shall mean Buyer’s account on the Zoozle Platform.
            </span>
          </h1>
          <p>
            &quot;<b>Zoozle Content</b>&quot; means all Content that Zoozle makes
            available through the Zoozle Platform and Zoozle E-Commerce Enabler,
            including any Content licensed from a third party.
          </p>
          <br />
          <h1>
            <b> “Zoozle Group Entities” </b>
            <span className="p">
              means all the subsidiaries and Affiliates of Zoozle.
            </span>
          </h1>
          <br />
          <p>
            Certain areas of the Zoozle Platform (and your access to or use of
            certain aspects of the Platform Services or Collective Content) may
            have different terms and conditions posted or may require you to
            agree with and accept additional terms and conditions. If there is a
            conflict between these Terms and terms and conditions posted for a
            specific area of the Zoozle Platform, or Collective Content, the
            latter terms and conditions will take precedence with respect to
            your use of or access to that area of the Zoozle Platform, or
            Collective Content.
          </p>
          <br />
          <h1 className="font-bold py-2">
            Conditions Relation to Your Use of Zoozle Platform
          </h1>
          <ol id="l1" className="list-decimal marker:font-bold pl-6">
            <li data-list-text="1.">
              <h1 className="font-bold">Your Account</h1>
              <p className="text-body">
                If You use the website, You are responsible for maintaining the
                confidentiality of Your account and password and for restricting
                access to Your computer to prevent unauthorized access to Your
                account. You agree to accept responsibility for all activities
                that occur under Your account or password. You should take all
                necessary steps to ensure that the password is kept confidential
                and secure and should inform us immediately if You have any
                reason to believe that Your password has become known to anyone
                else, or if the password is being, or is likely to be, used in
                an unauthorized manner. Please ensure that the details You
                provide us with are correct and complete and inform us
                immediately of any changes to the information that You provided
                when registering. You agree and acknowledge that You will use
                Your account on the website to purchase products only for Your
                personal use and not for business purposes. Further, under no
                circumstance will Zoozle call or ask for any password or OTP
                from the Buyer. In the event, if You share your password or OTP
                with any person or entity who may or may not be associated with
                Zoozle in relation to any order or Products purchased from the
                Zoozle Platform, it shall be your sole responsibility and Zoozle
                would not take any liability for the same.
              </p>
              <br />
            </li>
            <li data-list-text="2.">
              <h1 className="font-bold">Privacy</h1>
              <p className="text-body">
                Please go through our “Privacy Policy”, that governs Your visit
                to
                <Link
                  href="/"
                  className="text-blue-400 pl-1 underline"
                  target="_blank"
                >
                  www.zoozle.in{" "}
                </Link>
                , to understand our practices. The personal information / data
                provided to us by You during the course of usage of Zoozle
                Platform will be treated as strictly confidential and in
                accordance with the Privacy Policy and applicable laws and
                regulations. If You object to Your information being transferred
                or used, please do not use the Zoozle Platform.
              </p>
              <br />
            </li>
            <li data-list-text="3.">
              <h1 className="font-bold">Eligibility</h1>
              <p className="text-body">
                As per the Zoozle’s policies, You must be of at least 18
                (Eighteen) complete years of age to register, access or use the
                Zoozle Platform of Zoozle, and represents and warrants that You
                are of legal age to form a binding contract and meet all the
                eligibility requirements to enter into a valid contract. If the
                Zoozle suspect that You are under the age of 18 (Eighteen)
                complete years, the reporting mechanism available through this
                Site will be followed. If You are accessing or using the Site on
                behalf of another person or entity, You represent that they are
                authorized to accept these Buyer Terms and that the person or
                entity agrees to be responsible to Zoozle, if You or the other
                person or entity violates these Buyer Terms. If You do not meet
                any or all of the Buyer Terms, we request not to register with
                us.
              </p>
              <br></br>
            </li>
            <li data-list-text="4.">
              <h1 className="font-bold">Zoozle’s Role as a Facilitator</h1>
              <p className="text-body">
                The Zoozle Platform acts as a platform that Users utilize to
                independently meet and interact with one another for their
                transactions. Zoozle is not and cannot be a party to any
                transaction or dispute between users on the Platform. Zoozle is
                not a seller of the Products, agent, or insurer. Unless
                explicitly specified otherwise in the Zoozle Platform, Zoozle&apos;s
                responsibilities are limited to: (i) facilitating the
                availability of the Zoozle Platform and Zoozle E-Commerce
                Enabler Services; and (ii) serving as the limited payment
                collection agent of each Seller for the purpose of accepting
                payments from Buyer on behalf of the Seller. The Zoozle Platform
                can be used to facilitate and sale of Listed Products.
              </p>
              <br></br>
            </li>
            <li data-list-text="5.">
              <h1 className="font-bold">Services Provided</h1>
              <p className="text-body">
                Zoozle may provide the following services to the Buyers for
                facilitation of sale of Listed Products:
              </p>
              <ol id="l2" className="py-2">
                <li data-list-text="a.">
                  <p className="py-2">
                    a. Information and assistance in relation to the Listed
                    Products and sale thereof;
                  </p>
                </li>
                <li data-list-text="b.">
                  <p className="py-2">
                    b. Information in relation to the status of the order placed
                    by Buyers;
                  </p>
                </li>
                <li data-list-text="c.">
                  <p className="py-2">
                    c. Operating a customer help desk for other inquiries in
                    relation to products and orders; and
                  </p>
                </li>
                <li data-list-text="d.">
                  <p className="py-2">d. Buyers complaints and grievances.</p>
                  <p>
                    You agree and undertake to fully co-operate with the Zoozle
                    as reasonably required, in connection with any
                    customer-service functions undertaken by Zoozle. Further,
                    You agree and acknowledge that once an order is placed for
                    the Products on the Zoozle Platform and accepted by the
                    Seller, it cannot be cancelled.
                  </p>
                </li>
              </ol>
            </li>
            <li data-list-text="6.">
              <h1 className="font-bold">Return Policy</h1>
              <p className="text-body">
                Buyer agrees, acknowledges and undertakes that Zoozle has a
                definite return policy and it shall be followed in case of
                return of any Products to the Seller. Return policy is
                applicable to only those Products that the Buyers have received
                in a condition that is physically damaged, has missing parts or
                accessories, defective or substantially different from their
                description on the product detail page of Zoozle Platform.
                Return will be processed only when it is established that:
              </p>
              <br></br>
              <ol id="l3">
                <li data-list-text="a.">
                  <p>
                    a. the Product was not damaged while in the possession of
                    the Buyer;
                  </p>
                </li>
                <li data-list-text="b.">
                  <p>
                    b. the Product is not different from what was shipped to the
                    Buyer;
                  </p>
                </li>
                <li data-list-text="c.">
                  <p>
                    c. the Product returned by the Buyer is in its original
                    condition and form;
                  </p>
                </li>
                <li data-list-text="d.">
                  <p>
                    d. the Product is not covered in the non-returnable
                    category.
                  </p>
                  <p>
                    <br />
                  </p>
                  <p className="underline">Procedure for return of Products:</p>
                  <p>
                    To qualify for Zoozle’s return policy, Buyers have to record
                    a video of unboxing of the package delivered to them and
                    further upload this video on the return window of the
                    official website of Zoozle while filing for a return or
                    email on
                    <Link
                      href="mailto:order@zoozle.in"
                      className="s6"
                      target="_blank"
                    >
                      {" "}
                      order@zoozle.in.{" "}
                    </Link>
                    Return/replacement has to be claimed within 7 (seven) days
                    from the date of delivery of the Product. Zoozle will verify
                    the videos uploaded and will initiate the return process
                    post receipt of the return request and verification. Zoozle
                    follows a strict return procedure and will not accept any
                    return request without verifying the unboxing videos of the
                    damaged or wrong Products. Refund for the returned Products
                    will be initiated 15 (Fifteen) days after the Product is
                    received by the respective Seller and is duly verified. In
                    the event of any discrepancy found in the returned product,
                    return request shall stand cancelled.
                  </p>
                  <p>
                    <br />
                  </p>
                </li>
              </ol>
            </li>
            <li data-list-text="7.">
              <h1 className="font-bold">Access to Zoozle</h1>
              <p className="text-body">
                You agree, understand and acknowledge that your access to and
                use of the Zoozle Platform, cannot be assured/guaranteed due to
                the nature of the internet. Your access to the Platform Services
                available on the Zoozle Platform may also be occasionally
                interrupted, suspended or restricted, without prior notice, from
                time to time as a result of equipment malfunction, updating,
                maintenance, introduction of new Products or repair of the
                Platform Services available on the Zoozle Platform or any other
                reason within or outside of Zoozle’s control. Zoozle will
                attempt to &amp; if within its control, limit the frequency and
                duration of any such interruption, suspension or restriction.
                Zoozle reserves the right to suspend or discontinue the
                availability of the Platform Services available on the Zoozle
                Platform, any service or remove any content at any time at its
                sole discretion without prior notice. Zoozle may also impose
                limits on certain features and services or restrict the Your
                access to parts of or all of the Platform Services available on
                the Zoozle Platform without prior notice or liability. The
                Zoozle Platform shall not be used or relied upon for storage of
                the Your content and are directed to retain copies of all your
                content posted on the Zoozle Platform.
              </p>
            </li>
            <li data-list-text="8.">
              <h1 className="font-bold">Consent to Communication</h1>
              <p className="text-body">
                When You visit Zoozle Platform, You are communicating with
                Zoozle electronically. You will be required to provide a valid
                login ID and password while visiting the Site or using the
                Zoozle Platform. We may communicate with You by e-mail, SMS,
                phone call, chat, instant messages, text messages or by posting
                notices on the Zoozle Platform or by any other mode of
                communication. For contractual purposes, You consents to receive
                communications (including transactional, promotional and/or
                informative/commercial communication), from us with respect to
                Your use of the Zoozle Platform and/or order/s placed by You on
                the Zoozle Platform
              </p>
              <br></br>
            </li>
            <li data-list-text="9.">
              <h1 className="font-bold">Intellectual Property Rights</h1>
              <p className="text-body">
                This Policy does not convey to you any rights of ownership in or
                related to the Zoozle Platform and Zoozle E-Commerce Enabler
                Services, the Zoozle technology or the intellectual property
                rights owned by Zoozle. The Zoozle name, the Zoozle logo, and
                the product names associated with the Zoozle Platform and Zoozle
                E-Commerce Enabler Services are trademarks of Zoozle or third
                parties, and no right or license is granted to use them.
              </p>
              <br></br>
              <p className="text-body">
                Notwithstanding anything agreed between the Seller and the
                Buyer, both Seller and Buyer shall grant to Zoozle, and its
                Principals / Affiliates the irrevocable and unrestricted rights
                to such content throughout the world in any media,
                non-exclusive, royalty-free, without any consideration or
                compensation, perpetual, non-exclusive, fully transferable
                license, with right to sublicense, to use, publish, view, copy,
                adapt, modify, translate, create derivative works, license,
                sell, transfer, publicly display, publicly perform, transmit,
                stream, broadcast, access, reproduce, and distribute the
                copyrighted work (images/photographs/videos/audios) in any
                manner and medium for a) personal, non-profit uses; b)
                commercial uses; and c) editorial purposes.
              </p>
              <br></br>
              <p className="text-body">
                You agree that the rights granted above are irrevocable during
                the entire period of protection of the Your intellectual
                property rights associated with such content and material.
              </p>
              <br></br>
            </li>
            <li data-list-text="10.">
              <h1 className="font-bold">License to Access Zoozle Platform</h1>
              <p className="text-body">
                Subject to Your compliance with these Buyer Terms and on payment
                of applicable fees, if any, Zoozle grants You a limited
                non-exclusive, non-transferable license to access the Zoozle
                Platform, to (i) access and view any Zoozle Content solely for
                Your personal and non-commercial purposes and (ii) access and
                view any Seller Content to which You are permitted access,
                solely for Your personal and non-commercial purposes. You have
                no right to sublicense the license rights granted in this
                section.
              </p>
              <br></br>
              <p className="text-body">
                Zoozle reserves all rights in the Zoozle Platform not expressly
                granted to You by these Buyer Terms.
              </p>
              <br></br>
              <p className="text-body">
                You acknowledge that Zoozle reserves the right to terminate
                accounts that are inactive for an extended period of time. You
                further acknowledge that Zoozle reserves the right to change
                these general practices and limits at any time, in its sole
                discretion, with or without notice. Any unauthorized use will
                terminate the permission or license to the Buyer, to access this
                Zoozle Platform, granted by Zoozle and / or its principals &amp;
                Affiliates, as applicable.
              </p>
              <br></br>
            </li>
            <li data-list-text="11.">
              <h1 className="font-bold">Your Conduct</h1>
              <p className="text-body">
                You understand and agree that You are solely responsible for
                compliance with any and all laws, rules, regulations, tax
                obligations that may apply to Your use of the Zoozle Platform
                and Collective Content (photographs, audio, video, code,
                information, data, text, music, sound, graphics, messages or
                other materials included as Seller Content, that you submit,
                post, publish or display) anywhere on the Zoozle Platform.
              </p>
              <br></br>
              <p className="text-body">
                You must not use the Zoozle Platform in any way that causes, or
                is likely to cause, the Zoozle Platform or access to it to be
                interrupted, overburdened, damaged or impaired in any way. You
                understand that you, and not Zoozle, is responsible for all
                electronic communications and content sent from your computer /
                laptop / tablet / mobile or any similar communication device to
                us and You are permitted to use the Zoozle Platform for lawful
                purposes only. Zoozle reserves the right to investigate any
                content and take appropriate legal action against anyone who, in
                Zoozle’s sole discretion, violates this provision, including
                without limitation, removing the content from the Zoozle
                Platform, suspending or terminating the account of such
                violators and reporting the Buyers to the law enforcement
                authorities.
              </p>
              <br></br>
              <p className="text-body">
                You must not and agrees not to use the Zoozle Platform for any
                of the following:
              </p>
              <ol id="l4" className="list-[lower-roman] pl-8">
                <li data-list-text="a.">
                  <p>
                    To register for more than one Zoozle Account or register for
                    an Zoozle Account on behalf of an individual other than
                    yourself;
                  </p>
                </li>
                <li data-list-text="b.">
                  <p>
                    To recruit or otherwise solicit any Buyer, employee,
                    consultant or any other person professionally associated
                    with Zoozle to join third-party Services or Sites that are
                    competitive to Zoozle, without Zoozle&apos;s prior written
                    approval.
                  </p>
                </li>
                <li data-list-text="c.">
                  <p>
                    To interfere with, disrupt and/or damage the Zoozle Platform
                    or servers or networks connected to the Zoozle Platform, or
                    disobey any requirements, procedures, policies or
                    regulations of networks connected to the Zoozle Platform.
                  </p>
                </li>
                <li data-list-text="d.">
                  <p>
                    To access, tamper with, or use non-public areas of the
                    Zoozle Platform, Zoozle&apos;s computer systems, or the technical
                    delivery systems of Zoozle&apos;s providers.
                  </p>
                </li>
                <li data-list-text="e.">
                  <p>
                    To attempt to probe, scan, or test the vulnerability of any
                    Zoozle system or network or breach any security or
                    authentication measures.
                  </p>
                </li>
                <li data-list-text="f.">
                  <p>
                    To use manual or automated software, devices, scripts,
                    robots, backdoor or other means or processes to access,
                    &quot;scrape,&quot; &quot;crawl&quot; or &quot;spider&quot; any web pages or other
                    services contained in the Zoozle Platform or Collective
                    Content.
                  </p>
                </li>
                <li data-list-text="g.">
                  <p>
                    To avoid, bypass, remove, deactivate, impair, descramble, or
                    otherwise circumvent any technological measure implemented
                    by Zoozle or any of Zoozle&apos;s providers or any other third
                    party (including another Seller) to protect the Zoozle
                    Platform or Collective Content.
                  </p>
                </li>
                <li data-list-text="h.">
                  <p>
                    To forge any TCP/IP packet header or any part of the header
                    information in any email or newsgroup posting, or in any way
                    use the Zoozle Platform or Collective Content to send
                    altered, deceptive or false source-identifying information.
                  </p>
                </li>
                <li data-list-text="i.">
                  <p>
                    To systematically retrieve data or other content from our
                    Zoozle Platform to create or compile, directly or
                    indirectly, in single or multiple downloads, a collection,
                    compilation, database, directory or the like, whether by
                    manual methods, through the use of bots, crawlers, or
                    spiders, or otherwise.
                  </p>
                </li>
                <li data-list-text="j.">
                  <p>
                    To attempt to decipher, decompile, disassemble or reverse
                    engineer any of the software used to provide the Zoozle
                    Platform or Collective Content or to advocate, encourage, or
                    assist any third party in doing any of the foregoing.
                  </p>
                </li>
                <li data-list-text="k.">
                  <p>
                    If it contains, without limitation, any software viruses,
                    cancel bots, trojan horses, harmful code, flood pings,
                    denial-of-service attacks, backdoor, packet or IP spoofing,
                    forged routing or electronic mail address information or
                    similar methods or technology or any other files or programs
                    designed to interrupt, destroy or limit the functionality of
                    any communication device software or hardware or
                    telecommunications equipment.
                  </p>
                </li>
                <li data-list-text="l.">
                  <p>
                    To use, access or attempt to access our Zoozle Platform or
                    the Zoozle Application Program Interface (API) to: use,
                    expose, or allow to be used or exposed, any Zoozle Content:
                    (i) that is not publicly displayed by Zoozle in its search
                    results pages or Listed Products pages before a booking is
                    confirmed; (ii) in any way that is inconsistent with the
                    Zoozle Privacy Policy or Buyer Terms;
                  </p>
                </li>
                <li data-list-text="m.">
                  <p>
                    To upload, post, publish, submit or transmit any content
                    under any law or under contractual or fiduciary
                    relationships that (i) infringes, misappropriates or
                    violates any persons’ or entity or a third party&apos;s patent,
                    copyright, trademark, trade secret, moral rights,
                    intellectual property rights, rights of publicity, privacy
                    rights and contractual rights. (ii) If it is objectionable,
                    illegal, unlawful, harmful, threatening, harassing,
                    defamatory, tortious, excessively violent, vulgar, obscene,
                    pornographic, offensive (including but not limited to
                    material that is sexually explicit content or which promotes
                    racism, bigotry, hatred or physical harm), deceptive,
                    misleading, abusive, indecent, blasphemous, defamatory,
                    libellous, obscene, pornographic, pedophilic or menacing;
                    (iii) promotes discrimination, bigotry, racism, hatred,
                    harassment or harm against any individual or group; (iv) is
                    fraudulent, false, misleading or deceptive; (v) violates, or
                    encourages any conduct that would violate, any applicable
                    law or regulation or would promote any harmful and/or
                    criminal activity or give rise to civil liability; (vi) is
                    violent or threatening or promotes violence or actions that
                    are threatening to any other person; or (vii) promotes
                    illegal or harmful activities or substances; (viii) If it
                    causes annoyance, inconvenience or needless anxiety and
                    poses or creates a privacy or security risk to any person or
                    is otherwise injurious to third parties; (ix) Relates to or
                    promotes money laundering or gambling; (x) Harmful to minors
                    in any way; (xi) Threatens the unity, integrity, security or
                    sovereignty of India or friendly relations with foreign
                    States; political campaigning and likewise.
                  </p>
                </li>
                <li data-list-text="n.">
                  <p>
                    If it is ethically objectionable, disparaging or in breach
                    of copyright, trademark,
                  </p>
                  <p>
                    confidentiality, invasive of another’s privacy of any/all
                    other proprietary information or right;
                  </p>
                </li>
                <li data-list-text="o.">
                  <p>
                    To Impersonate any person or entity, or falsely state or
                    otherwise misrepresent yourself or your affiliation with a
                    person or entity; to transmit, distribute, post or submit
                    any information concerning any other person or entity,
                    including without limitation, photographs of others without
                    their permission, personal contact information or credit,
                    debit, calling card or account numbers.
                  </p>
                </li>
                <li data-list-text="p.">
                  <p>
                    To harvest, gather or collect email addresses or other
                    contact information of other Buyer’s or third-parties from
                    the Zoozle Platform by electronic or other means for the
                    purposes of sending unsolicited emails or other unsolicited
                    communications.
                  </p>
                </li>
                <li data-list-text="q.">
                  <p>
                    To &quot;stalk&quot; or “harass” any other Buyers of our Zoozle
                    Platform or Collective Content, or collect or store any
                    personally identifiable information about any other Buyers.
                  </p>
                </li>
                <li data-list-text="r.">
                  <p>
                    To contact a Buyer for any purpose other than asking a
                    question related to Listed Products.
                  </p>
                </li>
                <li data-list-text="s.">
                  <p>
                    To find a Seller or Buyer and then complete a sale of
                    Products independent of the Zoozle Platform, in order to
                    circumvent the obligation to pay any fees related to
                    Zoozle&apos;s provision of the sale of Products or for any other
                    reasons.
                  </p>
                </li>
                <li data-list-text="t.">
                  <p className="text-body">
                    In the sole judgment of Zoozle, is objectionable or which
                    restricts or inhibits any other person from using or
                    enjoying the service, or which may expose Zoozle or its
                    Buyer to any harm or liability of any type.
                  </p>
                  <p>
                    <br />
                  </p>
                  <p className="text-body">
                    Zoozle has the right to investigate and prosecute violations
                    of any of the above to the fullest extent of the law. Zoozle
                    may access, preserve and disclose any of your information if
                    we are required to do so by law, or if we believe in good
                    faith that it is reasonably necessary to (i) respond to
                    claims asserted against Zoozle or to comply with legal
                    process (for example, subpoenas or warrants), (ii) enforce
                    or administer our agreements, such as these, (iii) for fraud
                  </p>
                  <p className="text-body">
                    prevention, risk assessment, investigation, Buyer support,
                    product development and de-bugging purposes, or (iv) protect
                    the rights, property or safety of Zoozle, its members, or
                    members of the public.
                  </p>
                  <p>
                    <br />
                  </p>
                  <p className="text-body">
                    You acknowledge that Zoozle has no obligation to monitor
                    your access to or use of the Zoozle Platform or Collective
                    Content or to review or edit any Seller Content, but has the
                    right to do so for the purpose of operating and improving
                    the Zoozle Platform (including without limitation for fraud
                    prevention, risk assessment, investigation and Buyer support
                    purposes), to ensure your compliance with these Buyer Terms,
                    to comply with applicable law or the order or requirement of
                    a court, administrative agency or other governmental body,
                    to respond to content that it determines is otherwise
                    objectionable or as set forth in these Buyer Terms. Zoozle
                    reserves the right, at any time and without prior notice, to
                    remove or disable access to any Collective Content that
                    Zoozle, at its sole discretion, considers to be
                    objectionable for any reason, in violation of these Buyer
                    Terms or otherwise harmful to the Zoozle Platform.
                  </p>
                  <p>
                    <br />
                  </p>
                  <p className="text-body">
                    Any information or advertisements uploaded on, distributed
                    through, or linked, downloaded or accessed from any of the
                    services contained on the Zoozle Platform or any offer
                    displayed on or in connection with any service offered on
                    the Zoozle Platform (&quot; <b>Platform Information</b>&quot;) is
                    intended, solely to provide general information for the
                    personal use of the Buyers, who fully accept any and all
                    responsibility and liabilities arising from and out of the
                    use of such Platform Information.
                  </p>
                  <p>
                    <br />
                  </p>
                </li>
              </ol>
            </li>
            <li data-list-text="12.">
              <h1 className="font-bold">No Endorsement</h1>
              <p>
                Any references on the Zoozle Platform to a Seller being
                &quot;verified&quot; or &quot;connected&quot; (or similar language) only indicate
                that the Seller has completed a relevant verification process
                and does not represent anything else. Any such description is
                not an endorsement, certification or guarantee by Zoozle about
                any Seller, including of the Seller&apos;s identity and whether the
                Seller is trustworthy, safe or suitable. Instead, any such
                description is intended to be useful information for Buyers to
                evaluate when they make their own decisions about the identity
                and suitability of others whom they contact or interact with via
                the Zoozle Platform. We therefore recommend that Buyers always
                exercise due diligence and care when deciding whether to enter
                into a contract for Products. Accordingly, we encourage Buyers
                to communicate directly with Sellers on the Zoozle Platform
                regarding any sale or Listed Products made by the Sellers.
              </p>
              <br></br>
            </li>
            <li data-list-text="13.">
              <h1 className="font-bold">
                Reviews, Comments, Communications, and Other Content
              </h1>
              <p className="text-body">
                You may on the Zoozle Platform, post reviews, comments and other
                content; send communications; and submit suggestions, ideas,
                comments, questions, feedback or other information, as long as
                the content is not illegal, obscene, abusive, threatening,
                defamatory, invasive of privacy, infringing of intellectual
                property rights, or otherwise injurious to third parties, or
                objectionable and does not consist of or contain software
                viruses, political campaigning, commercial solicitation, chain
                letters, mass mailings, or any form of &quot;spam&quot;. In the event, You
                use a false e-mail address, impersonates any person or entity,
                or otherwise misleads as to the origin of any content. Zoozle
                reserves the right (but not the obligation) to remove, refuse,
                delete or edit any content that in the sole judgement of Zoozle
                violates these Buyer Terms and, or terminate the Your permission
                to access or use the Zoozle Platform.
              </p>
              <br></br>
            </li>
            <li data-list-text="14.">
              <h1 className="font-bold">
                Claims against Objectionable Content
              </h1>
              <p className="text-body">
                Because Zoozle lists many Products for sale offered by Sellers
                on the Zoozle Platform and hosts hundreds and thousands of
                comments, it is not possible for us to be aware of the contents
              </p>
              <p className="text-body">
                of each service listed for offer on sale, or each comment or
                review that is displayed. Accordingly, Zoozle operates on a
                &quot;notice and takedown&quot; basis.
              </p>
              <br></br>
              <p className="text-body">
                If we believe that any content on the Zoozle Platform is
                illegal, offensive (including but not limited to material that
                is sexually explicit content or which promotes racism, bigotry,
                hatred or physical harm), deceptive, misleading, abusive,
                indecent, harassing, blasphemous, defamatory, libellous,
                obscene, pornographic, pedophilic or menacing; ethnically
                objectionable, disparaging; or is otherwise injurious to third
                parties; or relates to or promotes money laundering or gambling;
                or is harmful to minors in any way; or impersonates another
                person; or threatens the unity, integrity, security or
                sovereignty of India or friendly relations with foreign States;
                or objectionable or otherwise unlawful in any manner whatsoever;
                or which consists of or contains software viruses, (&quot;{" "}
                <b>Objectionable Content</b>&quot;), Zoozle reserves the exclusive
                rights and authority to check, investigate and remove, if found
                necessary, such Objectionable Content immediately without any
                prior notice.
              </p>
              <br></br>
              <p className="text-body">
                If You believe a member is acting or has acted inappropriately,
                including but not limited to anyone who (i) engages in
                offensive, violent or sexually inappropriate behavior, (ii)
                suspect of stealing from you, or (iii) engages in any other
                disturbing conduct, You should immediately report to Zoozle by
                contacting us.
              </p>
              <br></br>
            </li>
            <li data-list-text="15.">
              <h1 className="font-bold">Disclaimer</h1>
              <p className="text-body">
                You agree understands and acknowledges that the Zoozle Platform
                is an online platform that enables You to search, select and
                make purchases of Products from the Sellers listed on the Zoozle
                Platform at the price/value indicated therein at any time from
                any location in India.
              </p>
              <p className="text-body">
                You further agree understands and acknowledges that Zoozle
                itself does not provide any Products and is only a facilitator
                and is not and cannot be a party to or control in any manner any
                transactions made by the Seller on the Zoozle Platform. Further,
                Zoozle holds no responsibility or assurity regarding the
                authenticity of price and quality of the Products of the Seller,
                in case of any discrepancy found in relation to the price or
                quality of the product, Zoozle shall not be held liable for any
                damage or loss occurred to You. In no event, any suit or
                proceedings or claims shall lie or be initiated by You, against
                Zoozle for any damage or loss caused, due to the usage or
                consumption of the Products of the Seller. However, Zoozle shall
                extend all their assistance in resolving the dispute between You
                and Seller amicably but shall not be a party of any dispute
                between You and Seller. It is expressly stated that Zoozle’s
                responsibilities are limited to the obligations as mentioned in
                these Buyer Terms. There are risks that the You must assume when
                dealing with the Seller (including those who may be acting under
                false pretenses). You agree to use the Zoozle Platform or
                collective content and that any/all these risks are borne by
                You, and not Zoozle.
              </p>
              <p className="text-body">
                You agrees &amp; acknowledges that: (i) Zoozle is not a party to
                any agreements entered between Seller and You, (iii) Zoozle
                provides and facilitates payment processing services, (iv)
                Zoozle is not a broker, agent, or insurer (iv) Zoozle doesn’t
                guarantee the quality, delivery and authenticity of the Listed
                Product purchased by a You through Zoozle Platform.
              </p>
              <p className="text-body">
                You further agree, understand, acknowledge, and undertake that
                You are accessing the Zoozle Platform and transacting at Your
                own risk and are using Your best and prudent judgment before
                entering into any transactions through the Zoozle Platform. The
                Zoozle E-Commerce Enabler Services provided are on an “as-is”
                and “as-available” basis. Without limiting the foregoing, Zoozle
                explicitly disclaims all warranties or representations whether
                expressed, implied or statutory, including but not limited to,
                the implied warranties of merchantability, quality,
              </p>
              <p className="text-body">
                suitability, accuracy, reliability, completeness, reliability,
                timeliness, truthfulness, performance, safety, fitness for a
                particular purpose, title and non-infringement, quiet enjoyment,
                and any warranties arising out of course of dealing or usage of
                trade or legality of the Zoozle Platform listed or displayed or
                transacted or the content (including service or pricing
                information and/or specifications) on the Zoozle Platform.
              </p>
              <br></br>
              <p className="text-body">
                Zoozle makes no warranty that the Zoozle Platform, Collective
                Content, including, but not limited to, (i) the type and quality
                of any information, or other purchases or obtained by You, may
                meet any specific or general requirements, (ii) the Zoozle
                E-Commerce Enabler Services may be uninterrupted, timely,
                secure, or error-free, (iii) the results that may be obtained
                from the use of the Zoozle E-Commerce Enabler Services will be
                of accuracy, reliability, timeliness, truthfulness, completeness
                of any collective content (iv) the Listed Products, may meet
                Your requirements or be delivered on an uninterrupted, secure,
                or error-free basis. No advice or information, whether oral or
                written, obtained from Zoozle or through the Zoozle Platform or
                collective content, will create any warranty not expressly made
                herein.
              </p>
              <br></br>
              <p className="text-body">
                Third parties other than Zoozle and its principals, affiliates
                &amp; subsidiaries may operate product stores and provide newer
                Products on Zoozle. In addition, we may provide links to the
                websites of affiliated companies and certain other businesses.
                However, we are not responsible for examining or evaluating, and
                we do not warrant or endorse the offerings of any of these
                individuals, businesses and organizations or the content of
                their websites. Zoozle does not assume any responsibility or
                liability for the actions, services, and content of any of these
                and any other third parties. You can tell when a third-party is
                involved in Your transactions, and we may share Your information
                related to those transactions with that third-party. You should
                carefully review their ‘Privacy Statement / Policy’ and their
                ‘Terms of Use’ before making any transactions and Zoozle will
                have no kind of obligations or liabilities in respect of any
                transactions done by the You on these websites.
              </p>
              <br></br>
              <p className="text-body">
                You agree to take reasonable precautions and shall be solely
                responsible for all of Your communications and interactions with
                the Sellers on the Zoozle Platform and with other persons with
                whom you communicate or interact as a result of Your use of the
                Zoozle Platform, particularly if You decide to meet offline or
                in person regardless of whether such meetings are organized by
                Zoozle or not. Notwithstanding anything herein, Zoozle is
                appointed as the limited payment collection agent on behalf of
                the Seller for the purpose of accepting payments from You only.
                Zoozle explicitly disclaims all liability for any act or
                omission of any You or other third party.
              </p>
              <br></br>
              <p className="text-body">
                While we have taken precautions to avoid inaccuracies in content
                on this Zoozle Platform, all content, information (including the
                price of Products), software and related graphics are provided
                as is, without warranty of any kind. We do not implicitly or
                explicitly support or endorse the sale or purchase of any
                Products on the Zoozle Platform. At no time shall any right,
                title or interest in the third-party Products sold through or
                displayed on the Zoozle Platform vest with Zoozle nor shall
                Zoozle have any kind of obligations or liabilities in respect of
                any transactions on the Zoozle Platform.
              </p>
              <br></br>
            </li>
            <li data-list-text="16.">
              <h1 className="font-bold">Links to third-party Websites</h1>
              <p className="text-body">
                The Zoozle Platform may contain links to third-party websites or
                resources. You acknowledge and agree that Zoozle is not
                responsible or liable for: (i) the availability or accuracy of
                such websites or resources; or (ii) the content, products, or
                Products on or available from such websites or resources. Links
                to such websites or resources do not imply any endorsement by
              </p>
              <p className="text-body">
                Zoozle of such websites or resources or the content, products,
                or Products available from such websites or resources. You
                acknowledge sole responsibility for and assume all risk arising
                from Your use of any such websites or resources or the Content,
                products or Products on or available from such websites or
                resources.
              </p>
              <br></br>
            </li>
            <li data-list-text="17.">
              <h1 className="font-bold">Third party beneficiary</h1>
              <p className="text-body">
                These Buyer Terms do not and are not intended to confer any
                rights or remedies upon any person other than the parties
                involved. Notwithstanding the foregoing, the parties agree that
                the payment gateway companies are third party beneficiaries of
                these Buyer Terms for purposes of enforcing provisions related
                to payments, but that their consent or agreement is not
                necessary for any changes or modifications to these Buyer Terms.
              </p>
              <br></br>
            </li>
            <li data-list-text="18.">
              <h1 className="font-bold">Limitation of Liability</h1>
              <p className="text-body">
                IN NO EVENT SHALL ZOOZLE BE LIABLE FOR ANY SPECIAL, INCIDENTAL,
                INDIRECT, OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION
                WITH THE BUYER TERMS, EVEN IF ZOOZLE HAS BEEN INFORMED IN
                ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.
              </p>
              <br></br>
            </li>
            <li data-list-text="19.">
              <h1 className="font-bold">Indemnity and Release</h1>
              <p className="text-body">
                You hereby expressly acknowledge, understand and agree to
                release, defend, indemnify and hold harmless, Zoozle, its
                principals, affiliates and subsidiaries &amp; and their
                respective founders, co-founders, directors, officers, agents
                and employees (collectively known as “ <b>Indemnities</b>”),
                harmless from any and/or all cost, damage, liability, claims or
                demands, losses, (direct or indirect losses, including but not
                restricted to, incidental, special, consequential, exemplary
                damages, or damages for loss of profits, loss of goodwill, use,
                data or other intangible losses), expenses, including reasonable
                legal and accounting fees, or other consequential losses,
                actions against any Seller Content, arising out of or in any way
                connected with i) Your access to or use of the Zoozle Platform,
                or Collective Content; ii) sale of Products; iii) Your violation
                of these Buyer Terms or Your violation of any rights of another,
                or actions of any kind and injury (including death) arising out
                of or relating to Your use of the Zoozle Platform; iv) The cost
                of procurement of substitute/alternate Products resulting from
                any data, information or Products purchased or obtained or
                messages received or transactions entered into through or from
                the access to or use of the Zoozle Platform; vii) Unauthorized
                access to or alteration of or transmissions of data of any other
                Seller Content; viii) Statements or conduct of any third party
                on the Zoozle Platform; ix) Any other matter relating to the
                service, loss of profits, revenue, contracts, anticipated
                savings, data, goodwill or wasted expenditure) or any other
                indirect or consequential loss that is not reasonably
                foreseeable to both, You and us when you commenced using the
                Zoozle Platform.
              </p>
              <br></br>
              <p className="text-body">
                You shall at no point hold Zoozle responsible for any delay or
                failure to comply with the obligations under these Buyer Terms,
                if there is any delay or failure arising from any cause/ reason
                which is beyond the reasonable control of Zoozle.
              </p>
              <br></br>
            </li>
            <li data-list-text="20.">
              <h1 className="font-bold">Zoozle Technology &amp; Software</h1>
              <p className="text-body">
                The technology and software underlying the Zoozle Platform is
                the sole property of Zoozle. Additionally, the Buyer Terms found
                here, apply to any software (including any updates or upgrades
                to the software and any related documentation) that we make
                available to You from time to time for Your use of Zoozle
                E-Commerce Enabler Services or any other services.
              </p>
              <p className="text-body">
                You may use the Zoozle Platform (including any updates or
                upgrades to the software, website, and any related
                documentation) solely for purposes of enabling Your use and
                enjoy the Zoozle E-Commerce Enabler Services as provided by
                Zoozle, and as permitted by the Buyer Terms. You will not
                incorporate any portion of the Zoozle Platform into Your own
                programs or compile any portion of it in combination with Your
                own program/s, transfer it for use with another service/s, or
                sell, rent, lease, lend, loan, distribute or sub-license the
                ‘Software’ or otherwise assign any rights to the ‘Software’ in
                whole or in part. You will not use the ‘Software’ for any
                illegal purpose. We may cease providing the Zoozle Platform and
                may terminate the rights to use the Zoozle Platform, in part or
                whole, at any time. Your right to use the ‘Software’ will
                automatically terminate without notice from us if You fail to
                comply with any of the ‘Zoozle Platform Terms’, the “Terms &amp;
                Conditions’’ or any other terms. Additional third-party terms
                contained within or distributed with certain the ‘Zoozle
                Platform’ that are specifically identified in related
                documentation may apply to that the ‘Zoozle Platform’ (or any
                other software incorporated with the ‘Zoozle Platform’) and will
                govern the use of such software in the event of a conflict with
                these Buyer Terms. All software used in any Zoozle E-Commerce
                Enabler Services is the property of Zoozle and/or its principals
                &amp; affiliates or its software suppliers and protected by laws
                of India including but not limited to any other applicable
                copyright laws.
              </p>
              <br></br>
              <p className="text-body">
                When You use the ‘Zoozle Platform’, you may also be using the
                services of one or more third parties, such as a wireless
                carrier or a mobile platform provider. Moreover, You will be
                subjected to the separate and different Privacy Policies and
                other Policies, Terms of Use, and fees of these third parties.
              </p>
              <br></br>
              <p className="text-body">
                You agree not to, and will not encourage, assist or authorize
                any other person to copy, modify, create a derivative work of,
                reverse engineer, reverse assemble, decompile or disassemble, or
                otherwise tamper with, the ‘Zoozle Platform’, whether in whole
                or in part, or create any derivative works from or of the
                ‘Zoozle Platform’ or attempt to discover any source code, sell,
                assign, sublicense, or otherwise transfer any right in the
                Zoozle Platform. Any rights not expressly granted herein are
                reserved by Zoozle.
              </p>
              <br></br>
              <p className="text-body">
                In order to keep the ‘Software’ up to date, we may offer
                automatic or manual updates at any time without any prior notice
                to You.
              </p>
              <br></br>
            </li>
            <li data-list-text="21.">
              <h1 className="font-bold">General</h1>
              <p className="text-body">
                The failure of Zoozle to enforce any right or provision of these
                Buyer Terms will not constitute a waiver of future enforcement
                of that right or provision. The waiver of any such right or
                provision will be effective only if in writing and signed by a
                duly authorized representative of Zoozle. Except as expressly
                set forth in these Buyer Terms, the exercise by either party of
                any of its remedies under these Buyer Terms will be without
                prejudice to its other remedies under these Buyer Terms or
                otherwise. If for any reason an arbitrator or a court of
                competent jurisdiction finds any provision of these Buyer Terms
                invalid or unenforceable, that provision will be enforced to the
                maximum extent permissible, and the other provisions of these
                Buyer Terms will remain in full force and effect.
              </p>
              <br></br>
            </li>
            <li data-list-text="22.">
              <h1 className="font-bold">Amendment of Buyer Terms</h1>
              <p className="text-body">
                Zoozle reserves the right, at its sole discretion, to make
                changes, amends, modifications, additions and likewise to the
                Zoozle Platform, policies and/or modify the Buyer Terms, or any
                policy or guidelines of Zoozle E-Commerce Enabler Services,
                including the Zoozle fees, at any time without prior notice. All
                modifications made in these Buyer Terms will be effective
              </p>
              <p className="text-body">
                immediately upon posting on the Zoozle Platform and will replace
                any prior version unless prior versions are specifically
                referred to or incorporated into the latest modification. Upon
                modification, Zoozle will post the changes on this page and will
                indicate at the top of this page the date these Buyer Terms were
                last revised. You agrees to routinely monitor the Buyer Terms to
                review and become familiar with such modifications. Your
                continued use of the Zoozle Platform, after such modification
                will be construed as manifestation of Your assent to the amends,
                modifications, additions and likewise to the Buyer Terms. You
                will be subject to the policies and Buyer Terms in force at the
                time that You use the Zoozle Platform or order Products from the
                Zoozle Platform, unless any change to those policies or these
                Buyer Terms is required to be made by law or government
                authority (in which case it will apply to orders previously
                placed by the Buyer). If any of these Buyer Terms is deemed
                invalid, void, or for any reason unenforceable, that condition
                will be deemed severable and will not affect the validity and
                enforceability of any remaining condition. If the modified Buyer
                Terms are not acceptable to You, Your only recourse is to cease
                using the Zoozle Platform.
              </p>
              <br></br>
            </li>
            <li data-list-text="23.">
              <h1 className="font-bold">Waiver</h1>
              <p className="text-body">
                In case, You breach any/all of these Buyer Terms at any given
                time, Zoozle reserves all rights and will always be entitled to
                take corrective measures and approach remedies to safeguard its
                interests.
              </p>
              <br></br>
            </li>
            <li data-list-text="24.">
              <h1 className="font-bold">
                Dispute Resolution &amp; Arbitration; Governing law; and
                Jurisdiction
              </h1>
              <p className="text-body">
                <u>Dispute Resolution </u>
                <u>
                  <i>&amp; </i>
                </u>
                <u>Arbitration</u>: You acknowledge and agree that any dispute,
                claim or controversy arising out of or relating to these Buyer
                Terms or the breach, termination, enforcement, interpretation or
                validity thereof, or to the use of the Zoozle Platform
                (collectively called here as &quot; <b>Disputes</b>
                &quot;) will be settled by (a) mutual <i>&amp; </i>amicable solutions{" "}
                <i>&amp; </i>
                settlements; or
              </p>
              <p className="text-body">
                (b) in accordance with provisions of the Arbitration and
                Conciliation Act, 1996.
              </p>
              <p className="text-body">
                When the arbitrator is appointed by any court, the arbitrator
                may or may not consolidate more than one person&apos;s claims and may
                or may not otherwise preside over any form of any className or
                representative proceeding. However, each party retains the right
                to seek injunctive or other equitable relief in, to prevent the
                actual or threatened infringement, misappropriation or violation
                of a party&apos;s copyrights, trademarks, trade secrets, patents, or
                other intellectual property rights.
              </p>
              <br></br>
              <p className="text-body">
                If this specific paragraph on Disputes and Arbitrations is held
                unenforceable by any court of law or any other relevant
                authority, then the entirety of this &quot;
                <i>
                  <b>Dispute Resolution</b>{" "}
                </i>
                &quot; section will be deemed void. Except as provided in the
                termination clauses herein, this section will survive any
                termination of these Buyer Terms.
              </p>
              <br></br>
              <p className="text-body">
                <u>Governing Law:</u> The Buyer Terms are governed and construed
                in accordance with the laws of India. Any arbitration process
                shall be subject to the ‘Arbitration <i>&amp; </i>Conciliation
                Act, 1996’ and if subsequently revised thereafter.
              </p>
              <br></br>
              <p className="text-body">
                Any party who desires to initiate arbitration must provide the
                other party with a written demand for arbitration as specified
                in the ‘Arbitration <i>&amp; </i>Conciliation Act, 1996’
                (Hereinafter called as
                <i>
                  <b>‘Act’</b>{" "}
                </i>
                ). The arbitrator will be either a retired judge or an attorney
                licensed to practice law in the city of Bangalore/Bengaluru in
                the state of Karnataka (INDIA) and will be selected by the
                parties from the respective courts roster of consumer dispute
                arbitrators.
              </p>
              <p className="text-body">
                <br />
              </p>
              <p className="text-body">
                The arbitrator may give its decision, within the time frame
                specified in the Act. The arbitrator&apos;s decision will include the
                essential findings and conclusions upon which the arbitrator
                based the
              </p>
              <p className="text-body">
                judgment on the arbitration, and this may be filed in any court
                having jurisdiction thereof. The arbitrator&apos;s judgement must be
                consistent with the Buyer Terms of the&quot;
                <i>
                  <b>Limitation of Liability</b>{" "}
                </i>
               &quot; section above as to the types and the amounts of damages for
                which a party may be held liable. The arbitrator may award
                declaratory or injunctive relief only in favour of the claimant
                and only to the extent necessary to provide relief warranted by
                the claimant&apos;s individual claim. However, both parties hereby
                waive all the rights it/they may have under applicable law to
                recover, lawyers&apos; fees and expenses if the arbitration judgement
                prevails. Both parties also agree to and shall be responsible to
                pay any arbitration filing, administrative and arbitrator fees
                as set forth in the Act.
              </p>
              <p className="text-body">
                Notwithstanding the provisions of the&quot;Amendment of
                Terms/Modification&quot; section above, if Zoozle changes this
               &quot;Dispute Resolution&quot; section after the date You first accepted
                these Buyer Terms (or accepted any subsequent changes to these
                Buyer Terms), you may reject any such change by sending us
                written notice (including by email) within 7 (Seven) working
                days of the date such change became effective, as indicated in
                the&quot;Last Updated Date&quot; above or, if sent, in the date of
                Zoozle&apos;s email to You notifying You of such change. By rejecting
                any change, You are agreeing that You will arbitrate any Dispute
                between You and Zoozle in accordance with the provisions of this
               &quot;Dispute Resolution&quot; section as of the date You first accepted
                these Buyer Terms (or accepted any subsequent changes to these
                Buyer Terms).
              </p>
              <br></br>
              <p className="text-body">
                <u>Jurisdiction:</u> These Buyer Terms and your use of the
                Zoozle Platform will be interpreted in accordance with the laws
                of India, without regard to any conflict-of-law provisions.
                Whenever the dispute, action, suit, or other legal proceedings
                are commenced to resolve any matters arising thereof and/or
                presented for arbitration in the courts, the sole <i>&amp; </i>
                exclusive jurisdiction will be with the courts at Bangalore,
                (Bengaluru), Karnataka, India.
              </p>
              <br></br>
            </li>
            <li data-list-text="25.">
              <h1 className="font-bold">Notices</h1>
              <p className="text-body">
                Any notices or other communications permitted or required
                hereunder, including those regarding modifications to these
                Buyer Terms, will be in writing and given by Zoozle (i) via
                email (in each case to the address that you provide) or (ii) by
                posting to the Site or via the application. For notices made by
                e-mail, the date of receipt will be deemed the date on which
                such notice is transmitted.
              </p>
              <br></br>
              <h1 className="text-body">Write to Zoozle on:</h1>
              <br></br>
              <p className="text-body">
                <Link
                  href="mailto:letstalk@zoozle.in"
                  className="s6"
                  target="_blank"
                >
                  Email: letstalk@zoozle.in
                </Link>
              </p>
              <p className="text-body">
                Address: 4 <span className="s9">th </span>Floor Leemans Complex
                Cunnigham Road Bangalore - 560051
              </p>
              <br></br>
            </li>
            <li data-list-text="26.">
              <h1 className="font-bold">Entire Agreement</h1>
              <p className="text-body">
                These Buyer Terms constitute the entire and exclusive
                understanding and agreement between Zoozle and You regarding the
                Zoozle Platform, Zoozle E-Commerce Enabler Services, Collective
                Content, and any sales or Listed Products made via the Zoozle
                Platform, and these Buyer Terms, supersede and replace any and
                all prior oral or written understandings or agreements between
                Zoozle and You.
              </p>
              <br></br>
            </li>
            <li data-list-text="27.">
              <h1 className="font-bold">Feedback</h1>
              <p className="text-body">
                We welcome and encourage You to provide feedback, comments and
                suggestions for improvements to the Zoozle Platform (&quot;{" "}
                <b>Feedback</b>&quot;).
              </p>
              <br></br>
              <p className="text-body">
                You may submit Feedback by emailing us, through
                <Link
                  href="mailto:letstalk@zoozle.in"
                  className="s6"
                  target="_blank"
                >
                  {" "}
                  letstalk@zoozle.in{" "}
                </Link>
                <span>
                  or by other means of communication. You acknowledge and agree
                  that all Feedback, You give us will be the sole and
                </span>
              </p>
              <p className="text-body">
                exclusive property of Zoozle and You hereby irrevocably assign
                to Zoozle and agree to irrevocably assign to Zoozle all of Your
                right, title, and interest in and to all Feedback, including
                without limitation all worldwide patent, copyright, trade
                secret, moral and other proprietary or intellectual property
                rights therein, and waive any moral rights You may have in such
                Feedback. At Zoozle&apos;s request and expense, You will execute
                documents and take such further acts as Zoozle may reasonably
                request to assist Zoozle to acquire, perfect, and maintain its
                intellectual property rights and other legal protections for the
                Feedback.
              </p>
            </li>
          </ol>
        </div>
      </div>
    </div>
  );
}

export default buyersTermsAndConditions;
